//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string IPAddress { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsCurrentLogin { get; set; }
        public Nullable<int> WrongTry { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
